use docs

proc docs_tree(ctx: TestContext, template_source: Str) [fs, error] -> Result[Path] {
  let root = test.temp_dir(ctx, name: "docs")?
  fp"{root}/docs/templates".mkdir()?
  fp"{root}/docs/templates/page.md".write(template_source)?
  fp"{root}/docs/snippets/tour/project/tests".mkdir()?
  fp"{root}/docs/snippets/tour/01-greet.xsh".write("""print "hello"
""")?
  fp"{root}/docs/snippets/tour/02-proc.xsh".write("""# platform: linux
print "linux only"
""")?
  fp"{root}/docs/snippets/tour/project/xsht-config.ini".write("""test_roots = tests
""")?
  fp"{root}/docs/snippets/tour/project/tests/test-unit.xsh".write("""test passes {
  assert 1 + 1 == 2
}
""")?
  fp"{root}/docs/snippets/spec/rejected".mkdir()?
  fp"{root}/docs/snippets/spec/01-fragment.xsh".write("""pure double(n: Int) -> Int {
  # begin example
  n * 2
  # end example
}

const offset = 1
# begin example

let total = double(20) + offset

# end example
print $total
""")?
  fp"{root}/docs/snippets/spec/rejected/02-undefined.xsh".write("""print $missing # error: check.unresolved-name
""")?
  root
}

pure tools(ctx: TestContext) -> docs.DocTools {
  docs.DocTools(xsh: ctx.xsh_bin, xsht: fp"{ctx.xsh_bin.parent()}/xsht")
}

test test_docs_check_names_stale_output_until_generate_rewrites_it { |ctx|
  let root = docs_tree(
    ctx,
    """```xsh
{{.tour.greet.source}}
```

```text
{{.tour.greet.output}}
```

{{.project.tests_test_unit.path}} ({{len .lints}} lints)
""",
  )?

  match docs.check(root, tools(ctx)) {
    Ok(_) => assert false, "a missing generated file must be stale"
    Err(error) => assert "stale generated docs: docs/page.md;" in error.message, error.message
  }

  docs.generate(root, tools(ctx))?
  let page = fp"{root}/docs/page.md".read_text()?
  assert page.starts_with("<!-- Generated by make docs from docs/templates/page.md;"), page
  assert """```xsh
print "hello"
```

```text
hello
```

tests/test-unit.xsh (""" in page, page
  docs.check(root, tools(ctx))?
}

test test_docs_show_dedented_example_regions_and_run_the_whole_snippet { |ctx|
  let root = docs_tree(
    ctx,
    """```xsh
{{.spec.fragment.source}}
```

```text
{{.spec.fragment.output}}
```
""",
  )?

  docs.generate(root, tools(ctx))?
  let page = fp"{root}/docs/page.md".read_text()?
  assert """```xsh
n * 2
let total = double(20) + offset
```

```text
41
```""" in page, page
  docs.check(root, tools(ctx))?
}

test test_docs_check_requires_exactly_the_annotated_diagnostics { |ctx|
  let root = docs_tree(ctx, "")?
  docs.generate(root, tools(ctx))?
  docs.check(root, tools(ctx))?

  fp"{root}/docs/snippets/spec/rejected/02-undefined.xsh".write("""print $missing # error: check.dynamic-boundary
""")?
  match docs.check(root, tools(ctx)) {
    Ok(_) => assert false, "a rejected snippet must report the code its comment names"
    Err(error) => assert "02-undefined.xsh lacks [1: check.dynamic-boundary] and reports [1: check.unresolved-name]" in error.message, error.message
  }

  fp"{root}/docs/snippets/spec/rejected/02-undefined.xsh".write("""print "fine"
""")?
  match docs.check(root, tools(ctx)) {
    Ok(_) => assert false, "a rejected snippet must name its expected error"
    Err(error) => assert "02-undefined.xsh is rejected but names no `# error: CODE`" in error.message, error.message
  }

  fp"{root}/docs/snippets/spec/rejected/02-undefined.xsh".remove()?
  fp"{root}/docs/snippets/spec/02-undefined.xsh".write("""print $missing
""")?
  match docs.check(root, tools(ctx)) {
    Ok(_) => assert false, "a snippet outside rejected/ must check clean"
    Err(error) => assert "02-undefined.xsh lacks [] and reports [1: check.unresolved-name]" in error.message, error.message
  }
}

test test_docs_refuse_an_unclosed_example_region { |ctx|
  let root = docs_tree(ctx, "")?
  fp"{root}/docs/snippets/spec/03-open.xsh".write("""# begin example
print "open"
""")?

  match docs.generate(root, tools(ctx)) {
    Ok(_) => assert false, "an unclosed region must fail"
    Err(error) => assert "03-open.xsh leaves an example region open" in error.message, error.message
  }
}

test test_docs_refuse_to_show_output_of_a_platform_specific_snippet { |ctx|
  let root = docs_tree(
    ctx,
    """{{.tour.proc.output}}
""",
  )?

  match docs.generate(root, tools(ctx)) {
    Ok(_) => assert false, "a linux-only snippet must not run"
    Err(error) => assert "output of platform-specific 02-proc.xsh" in error.message, error.message
  }
}
