use docs

proc docs_tree(ctx: TestContext, template_source: Str) [fs, error] -> Result[Path] {
  let root = test.temp_dir(ctx, name: "docs")?
  fp"${root}/docs/templates".mkdir()?
  fp"${root}/docs/templates/page.md".write(template_source)?
  fp"${root}/docs/snippets/tour/project/tests".mkdir()?
  fp"${root}/docs/snippets/tour/01-greet.xsh".write("""print "hello"
""")?
  fp"${root}/docs/snippets/tour/02-proc.xsh".write("""# platform: linux
print "linux only"
""")?
  fp"${root}/docs/snippets/tour/project/xsht-config.ini".write("""test_roots = tests
""")?
  fp"${root}/docs/snippets/tour/project/tests/test-unit.xsh".write("""test passes {
  assert 1 + 1 == 2
}
""")?
  root
}

pure tools(ctx: TestContext) -> docs.DocTools {
  docs.DocTools(xsh: ctx.xsh_bin, xsht: fp"${ctx.xsh_bin.parent()}/xsht")
}

test test_docs_check_names_stale_output_until_generate_rewrites_it { |ctx|
  let root = docs_tree(
    ctx,
    """```xsh
{{.snippets.greet.source}}
```

```text
{{.snippets.greet.output}}
```

{{.project.tests_test_unit.path}} ({{len .lints}} lints)
""",
  )?

  match docs.check(root, tools(ctx)) {
    Ok(_) => assert false, "a missing generated file must be stale"
    Err(error) => assert "stale generated docs: docs/page.md;" in error.message, error.message
  }

  docs.generate(root, tools(ctx))?
  let page = fp"${root}/docs/page.md".read_text()?
  assert page.starts_with("<!-- Generated by make docs from docs/templates/page.md;"), page
  assert """```xsh
print "hello"
```

```text
hello
```

tests/test-unit.xsh (""" in page, page
  docs.check(root, tools(ctx))?
}

test test_docs_refuse_to_show_output_of_a_platform_specific_snippet { |ctx|
  let root = docs_tree(
    ctx,
    """{{.snippets.proc.output}}
""",
  )?

  match docs.generate(root, tools(ctx)) {
    Ok(_) => assert false, "a linux-only snippet must not run"
    Err(error) => assert "output of platform-specific 02-proc.xsh" in error.message, error.message
  }
}
