[package]
name = "xsh-multicall"
version = "0.0.1"
edition = "2024"
publish = false

[features]
default = ["native-tests", "net", "tools"]
native-tests = ["xsh/native-tests", "xsht/native-tests"]
net = ["xsh/net"]
tools = ["xsh/tools"]
benchmark-support = ["xshi/benchmark-support"]

[dependencies]
xsh = { path = "../..", default-features = false }
xshi = { path = "../xshi", default-features = false }
xsht = { path = "../xsht", default-features = false }

[target.'cfg(target_os = "linux")'.dependencies]
mimalloc = "0.1.52"

[dev-dependencies]
divan = "0.1.21"
tempfile = "3"

[[bench]]
name = "bench"
harness = false
required-features = ["benchmark-support"]

[lints.clippy]
nursery = { level = "allow", priority = -2 }
pedantic = { level = "allow", priority = -2 }
complexity = { level = "deny", priority = -2 }
correctness = { level = "deny", priority = -2 }
perf = { level = "deny", priority = -2 }
restriction = { level = "allow", priority = -2 }
suspicious = { level = "deny", priority = -2 }
cargo = { level = "deny", priority = -1 }
style = { level = "deny", priority = -1 }
blanket_clippy_restriction_lints = { level = "allow", priority = 0 }
wildcard_imports = { level = "deny", priority = 0 }
disallowed_types = { level = "deny", priority = 1 }
single_call_fn = { level = "allow", priority = 1 }
multiple_crate_versions = { level = "allow", priority = 1 }
result_large_err = { level = "allow", priority = 1 }
too_many_arguments = { level = "allow", priority = 1 }
type_complexity = { level = "allow", priority = 1 }
