##! Generated documentation: renders each `docs/templates/REL` into `docs/REL`
##! with the stdlib `template` module, and checks that committed output is current.
##!
##! Template data is one record:
##! - `tour.NAME` and `spec.NAME`: `{source, output, platform}` for the snippet
##!   `docs/snippets/COLLECTION/NN-NAME.xsh` (`-` in NAME becomes `_`). `source` is the whole
##!   file, or the concatenation of its `# begin example` ... `# end example` regions,
##!   each dedented, so a fragment is checked inside a wrapper program the document
##!   does not show. `output` is the snippet's stdout when some template references
##!   `.COLLECTION.NAME.output`, and null otherwise, so only shown outputs run. A snippet
##!   whose first line is `# platform: linux` is checked but never run; any output
##!   shown for it is literal text in the template.
##! - `docs/snippets/COLLECTION/rejected/NN-NAME.xsh` snippets show code that must fail to
##!   check: `check` requires exactly the diagnostics their `# error: CODE` comments
##!   name, on those lines, and every other snippet must check clean. Other `.xsh`
##!   files directly in a collection directory are support modules that snippets import;
##!   their names must not start with a digit.
##! - `project.KEY`: `{path, source}` for each file of `docs/snippets/tour/project/`,
##!   keyed by its relative path without the extension, non-alphanumeric runs as `_`.
##! - `stdlib`, `cli`, `lints`, `facets`, `grammar`: reference data read from `xsht api`,
##!   the binaries' help, `xsht lint --list`, the `language:facet` API items, and
##!   `xsht grammar --format json`.
##!
##! `docs/user-tour.html` is not a template: `tour_html` renders it from the
##! rendered `docs/user-tour.md`.
use context
use stage as stages
use tour_html

## A generated-documentation failure, rendered at the development command boundary.
export error DocsError = Stale(message: Str) | Snippet(message: Str) | Layout(message: Str)

## The binaries that render and verify the documentation.
export type DocTools = {xsh: Path, xsht: Path}

type Snippet = {source: Str, output: Str?, platform: Str}

type SnippetFile = {name: Str, key: Str, path: Path, rejected: Bool}

type ProjectFile = {path: Str, source: Str}

type Rendered = {rel: Str, text: Str}

type Overloads = {name: Str, overloads: Int}

type ModuleIndex = {name: Str, functions: List[Overloads]}

type ReceiverIndex = {name: Str, methods: List[Overloads]}

type ApiSummary = {modules: List[ModuleIndex], method_receivers: List[ReceiverIndex], records: List[Str]}

type ApiMatch = {kind: Str, summary: Str, signatures: List[Str]}

type ApiAnswer = {query: Str, matches: List[ApiMatch]}

type IndexLine = {signature: Str, summary: Str}

type LintCode = {code: Str, summary: Str}

type FacetMatch = {id: Str, summary: Str, contract: Str}

type FacetAnswer = {query: Str, matches: List[FacetMatch]}

type FacetRow = {name: Str, summary: Str, contract: Str}

type GrammarSection = {title: Str, ebnf: Str}

type OperatorLevel = {precedence: Int, operators: Str, associativity: Str, families: Str}

type GrammarTerminal = {name: Str, description: Str}

type QuotedForm = {prefix: Str, terminal: Str, raw: Str}

type StageRow = {name: Str, block: Str, inline: Str}

type GrammarReference = {
  sections: List[GrammarSection],
  operators: List[OperatorLevel],
  prefix_precedence: Int,
  continuation: Str,
  keywords: Str,
  terminals: List[GrammarTerminal],
  literals: List[QuotedForm],
  duration_suffixes: Str,
  stages: List[StageRow],
  run_forms: List[Str],
  run_options: Str,
}

const snippet_name = rx"^[0-9][0-9]-([a-z0-9-]+)\.xsh$"

const numbered_name = rx"^[0-9]"

# Snippet collections, each rendered as `.COLLECTION.NAME` from `docs/snippets/COLLECTION/`.
const snippet_collections = ["tour", "spec"]

const output_reference = rx"\.(tour|spec)\.[a-z0-9_]+\.output"

const region_begin = "# begin example"

const region_end = "# end example"

const leading_spaces = rx"^( *)"

const error_annotation = rx"# error: ([a-z0-9._-]+)$"

# `xsht check` reports a diagnostic as `SEVERITY[CODE]: message` followed by an
# indented `PATH:LINE:COLUMN` line.
const diagnostic_header = rx"^[a-z]+\[([a-z0-9._-]+)\]: "

const diagnostic_location = rx"^ +.+:([0-9]+):[0-9]+$"

const command_heading = rx"^([a-z]+) — "

# Modules that are internal host support rather than user API.
const internal_modules = ["applet"]

const tour_markdown = "user-tour.md"

const tour_page = "user-tour.html"

pure header(rel: Str) -> Str {
  let hint = if rel == tour_markdown {
    "edit the template and docs/snippets/tour/."
  } else if rel == tour_page {
    "edit the tour template, docs/snippets/tour/, or dev/tour_html.xsh."
  } else if rel == "SPEC.md" {
    "edit the template and docs/snippets/spec/."
  } else {
    "edit the template or the code it documents."
  }
  let source = if rel == tour_page { tour_markdown } else { rel }
  f"<!-- Generated by make docs from docs/templates/{source}; {hint} -->"
}

# Text without its final newline, for embedding between fence lines.
pure body(text: Str) -> Str {
  text.lines().join("\n")
}

pure field_key(rel: Str) -> Str {
  rx"[^A-Za-z0-9]+".replace(rx"\.[A-Za-z0-9]+$".replace(rel, ""), "_")
}

# The names of the `collection` snippets whose output some template shows.
pure shown_outputs(templates: List[Str], collection: Str) -> List[Str] {
  var names: List[Str] = []
  for source in templates {
    for found in output_reference.find(source) {
      let parts = found.text.split(".")
      if parts[1] == collection {
        names += [parts[2]]
      }
    }
  }

  names
}

pure indent(line: Str) -> Int {
  leading_spaces.captures(line)[1].byte_len()
}

# Region lines without their common leading spaces; blank lines become empty.
pure dedent(lines: List[Str]) -> List[Str] {
  var width = -1
  for line in lines {
    if line.trim() != "" and (width < 0 or indent(line) < width) {
      width = indent(line)
    }
  }

  [if line.trim() == "" { "" } else { line.byte_slice(width) } for line in lines]
}

# Region lines without blank lines at either end, such as the one the
# formatter puts after a declaration that ends a region.
pure trim_blank_edges(lines: List[Str]) -> List[Str] {
  var start = 0
  var end = lines.len()
  while start < end and lines[start].trim() == "" {
    start += 1
  }

  while end > start and lines[end - 1].trim() == "" {
    end -= 1
  }

  lines[start..end]
}

# The text a document shows for a snippet: the whole file when it has no
# example region, otherwise its regions in order.
pure shown_source(name: Str, source: Str) -> Result[Str] {
  var shown: List[Str] = []
  var region: List[Str] = []
  var inside = false
  var regions = 0
  for line in source.lines() {
    if line.trim() == region_begin {
      guard ! inside else {
        return Err(DocsError.Layout(message: f"{name} opens an example region inside another"))
      }

      inside = true
      region = []
    } else if line.trim() == region_end {
      guard inside and region.len() > 0 else {
        return Err(DocsError.Layout(message: f"{name} closes an example region that is not open or is empty"))
      }

      shown += dedent(trim_blank_edges(region))
      inside = false
      regions += 1
    } else if inside {
      region += [line]
    }
  }

  guard ! inside else {
    return Err(DocsError.Layout(message: f"{name} leaves an example region open"))
  }

  if regions == 0 { body(source) } else { shown.join("\n") }
}

# Runs a trusted repository snippet in an empty directory with only `PATH` set.
# The child gets its working directory from its command plan rather than a
# `cd` scope, which would serialize the `par-map` workers.
proc run_snippet(xsh: Path, file: Path, search_path: Str) [fs, process, error] -> Result[Str] {
  let sandbox = fs.tempdir()?
  defer sandbox.close()?
  let capture = fs.tempdir()?
  defer capture.close()?
  let stdout = fp"{capture.host_path()?}/stdout"
  let stderr = fp"{capture.host_path()?}/stderr"
  let argv = ["-i", f"PATH={search_path}", xsh.display(), file.display()]
  let plan = process.command_argv(/usr/bin/env, argv, cwd: sandbox.host_path()?, stdout:, stderr:, timeout: 60s)
  guard process.run(plan)?.ok else {
    return Err(DocsError.Snippet(message: f"{file.name()} failed: {stderr.read_text()?.trim()}"))
  }

  body(stdout.read_text()?)
}

proc snippet_files(dir: Path) [fs, error] -> Result[List[SnippetFile]] {
  let rejected_dir = fp"{dir}/rejected"
  var files: List[SnippetFile] = []
  for entry in fs.files(dir, exts: ["xsh"])? |> sort-by .name {
    let parent = entry.path.parent()
    continue unless parent == dir or parent == rejected_dir
    let parts = snippet_name.captures(entry.name)
    if parts.len() == 2 {
      let key = parts[1].replace("-", "_")
      files += [SnippetFile(name: entry.name, key:, path: entry.path, rejected: parent == rejected_dir)]
    } else if numbered_name.matches(entry.name) or parent == rejected_dir {
      return Err(DocsError.Layout(message: f"snippet {entry.name} is not named NN-name.xsh"))
    }
  }

  files
}

proc snippets(dir: Path, xsh: Path, shown: List[Str]) [fs, process, env, error] -> Result[Map[Str, Snippet]] {
  let search_path = env.get_or("PATH", "")?
  let collected = snippet_files(dir)?
    |> par-map(jobs: 8) { |file|
      let source = file.path.read_text()?
      let platform = if (source.lines().get(0) ?? "") == "# platform: linux" { "linux" } else { "any" }
      let output: Str? = if file.key not in shown {
        null
      } else if platform != "any" {
        return Err(DocsError.Snippet(message: f"a template shows the output of platform-specific {file.name}"))
      } else if file.rejected {
        return Err(DocsError.Snippet(message: f"a template shows the output of rejected {file.name}"))
      } else {
        run_snippet(xsh, file.path, search_path)?
      }

      {name: file.key, snippet: Snippet(source: shown_source(file.name, source)?, output:, platform:)}
    }

  var table: Map[Str, Snippet] = {}
  for {name, snippet} in collected {
    guard name not in table else {
      return Err(DocsError.Layout(message: f"two {dir.name()} snippets are named {name}"))
    }

    table[name] = snippet
  }

  for name in shown {
    guard name in table else {
      return Err(DocsError.Layout(message: f"a template shows the output of unknown snippet {dir.name()}.{name}"))
    }
  }

  table
}

# `LINE: CODE` for each `# error: CODE` comment in a snippet.
pure expected_diagnostics(source: Str) -> List[Str] {
  let lines = source.lines()
  var expected: List[Str] = []
  for index in range(lines.len()) {
    if let [_, code] = error_annotation.captures(lines[index]) {
      expected += [f"{index + 1}: {code}"]
    }
  }

  expected
}

# `LINE: CODE` for each diagnostic in the `xsht check` report on one file.
pure reported_diagnostics(report: Str) -> List[Str] {
  var reported: List[Str] = []
  var code = ""
  for text in report.lines() {
    if let [_, line] = diagnostic_location.captures(text) {
      if code != "" {
        reported += [f"{line}: {code}"]
      }
    }

    let heading = diagnostic_header.captures(text)
    code = if heading.len() == 2 { heading[1] } else { "" }
  }

  reported
}

# Checks each snippet of a collection on its own: a rejected snippet must report exactly
# the diagnostics its `# error: CODE` comments name, on those lines, and any other
# snippet must report nothing.
proc check_snippet_diagnostics(dir: Path, xsht: Path) [fs, process, error] {
  let failures = snippet_files(dir)?
    |> par-map(jobs: 4) { |file|
      let expected = expected_diagnostics(file.path.read_text()?)
      let result = run.capture --text $xsht check $file.path ?
      let reported = reported_diagnostics(result.stderr)
      let missing = [d for d in expected if d not in reported]
      let unexpected = [d for d in reported if d not in expected]
      if file.rejected and expected.len() == 0 {
        f"{file.name} is rejected but names no `# error: CODE`"
      } else if ! file.rejected and expected.len() > 0 {
        f"{file.name} names an expected error outside rejected/"
      } else if ! result.status.ok and reported.len() == 0 {
        f"xsht check {file.name} failed: {result.stderr.trim()}"
      } else if missing.len() + unexpected.len() > 0 {
        f"{file.name} lacks [{missing.join(", ")}] and reports [{unexpected.join(", ")}]"
      } else {
        ""
      }
    }

  let problems = [failure for failure in failures if failure != ""]
  guard problems.len() == 0 else {
    return Err(DocsError.Snippet(message: f"snippet diagnostics differ: {problems.join("; ")}"))
  }
}

proc project(root: Path) [fs, error] -> Result[Map[Str, ProjectFile]] {
  let base = fp"{root}/docs/snippets/tour/project"
  var files: Map[Str, ProjectFile] = {}
  for entry in fs.files(base)? {
    let rel = entry.path.relative_to(base).display()
    files[field_key(rel)] = ProjectFile(path: rel, source: body(entry.path.read_text()?))
  }

  files
}

pure index_line(found: ApiMatch) -> IndexLine {
  let extra = found.signatures.len() - 1
  let signature = found.signatures.get(0) ?? ""
  let suffix = if extra > 0 { f" (+{extra} overloads)" } else { "" }
  IndexLine(signature: signature + suffix, summary: found.summary)
}

proc stdlib(xsht: Path) [process, error] -> Result[Record] {
  let summary = json.decode(run.text $xsht api summary --format jsonl?)?.require(ApiSummary)?
  let modules = [m for m in summary.modules if m.name not in internal_modules]
  var queries = [f"module:{m.name}" for m in modules]
  for receiver in summary.method_receivers {
    let owner = receiver.name.fields()[0]
    queries += [f"method:{owner}.{m.name}" for m in receiver.methods if " " not in m.name]
  }

  queries += [f"record:{name}" for name in summary.records]

  var answers: Map[Str, List[ApiMatch]] = {}
  for line in run.text $xsht api --strict --format jsonl @queries?.lines() {
    let answer = json.decode(line)?.require(ApiAnswer)?
    answers[answer.query] = answer.matches
  }

  var module_rows = []
  for m in modules {
    let matches = answers[f"module:{m.name}"]
    module_rows += [
      {
        name: m.name,
        summary: [found.summary for found in matches if found.kind == "module"].get(0) ?? "",
        functions: [index_line(found) for found in matches if found.kind == "module-function"],
      },
    ]
  }

  var receiver_rows = []
  for receiver in summary.method_receivers {
    let owner = receiver.name.fields()[0]
    let lines = [
      index_line(found)
      for m in receiver.methods
      if " " not in m.name
      for found in answers[f"method:{owner}.{m.name}"]
    ]
    receiver_rows += [{name: receiver.name, methods: lines}]
  }

  let records = [
    index_line(found)
    for name in summary.records
    for found in answers[f"record:{name}"]
  ]
  {modules: module_rows, receivers: receiver_rows, records}
}

# Help text without its leading `NAME VERSION` line, so releases do not stale the reference.
pure unversioned(help: Str) -> Str {
  body(help).lines()[1..].join("\n").trim()
}

pure line_index(lines: List[Str], heading: Str) -> Int {
  for index in range(lines.len()) {
    return index when lines[index] == heading
  }

  -1
}

proc cli_reference(tools: DocTools) [process, error] -> Result[Record] {
  let lines = unversioned(run.text $tools.xsht --help?).lines()
  let reference = line_index(lines, "Command reference:")
  let workflows = line_index(lines, "Common workflows:")
  guard 0 < reference < workflows else {
    return Err(DocsError.Layout(message: "`xsht --help` lacks its command reference or workflows section"))
  }

  var commands = []
  for line in lines[reference..workflows] {
    if let [_, name] = command_heading.captures(line) {
      commands += [{name, help: body(run.text $tools.xsht help $name?)}]
    }
  }

  {
    xsh: unversioned(run.text $tools.xsh --help?),
    xsht: lines[..reference].join("\n").trim(),
    commands,
    workflows: [line for line in lines[workflows + 1..] if line != ""].join("\n"),
  }
}

proc lints(xsht: Path) [process, error] -> Result[List[LintCode]] {
  [json.decode(line)?.require(LintCode)? for line in (run.text $xsht lint --list --format jsonl)?.lines()]
}

# The built-in error facet vocabulary, one row per `language.facet.NAME` API item.
proc facets(xsht: Path) [process, error] -> Result[List[FacetRow]] {
  let answer = json.decode(run.text $xsht api --strict --format jsonl "language:facet"?)?.require(FacetAnswer)?
  [FacetRow(name: found.id.split(".")[2], summary: found.summary, contract: found.contract) for found in answer.matches]
}

proc grammar_reference(xsht: Path) [process, error] -> Result[GrammarReference] {
  json.decode(run.text $xsht grammar --format json?)?.require()
}

# Renders every template with freshly collected data.
proc render(root: Path, tools: DocTools) [fs, process, env, error] -> Result[List[Rendered]] {
  let templates_dir = fp"{root}/docs/templates"
  let templates = fs.files(templates_dir, exts: ["md"])? |> sort-by .name
  let sources = [{rel: t.path.relative_to(templates_dir).display(), source: t.path.read_text()?} for t in templates]
  let shown = [t.source for t in sources]
  let data = {
    tour: snippets(fp"{root}/docs/snippets/tour", tools.xsh, shown_outputs(shown, "tour"))?,
    spec: snippets(fp"{root}/docs/snippets/spec", tools.xsh, shown_outputs(shown, "spec"))?,
    project: project(root)?,
    stdlib: stdlib(tools.xsht)?,
    cli: cli_reference(tools)?,
    lints: lints(tools.xsht)?,
    facets: facets(tools.xsht)?,
    grammar: grammar_reference(tools.xsht)?,
  }

  let pages = [
    Rendered(
      rel: t.rel,
      text: [
        header(t.rel),
        "",
        ctx f"rendering docs/templates/{t.rel}" {
          template.render(t.source, data)?
        },
      ].join("\n"),
    )
    for t in sources
  ]

  var documents = pages
  for page in pages {
    if page.rel == tour_markdown {
      let html = ctx f"rendering docs/{tour_page}" {
        tour_html.render(page.text, tools.xsht)?
      }
      documents += [Rendered(rel: tour_page, text: [header(tour_page), html].join("\n"))]
    }
  }

  documents
}

## Regenerates every generated document under `docs/`, rewriting only files that changed.
export proc generate(root: Path, tools: DocTools) [fs, process, env, error, io] -> Result[Unit] {
  for doc in render(root, tools)? {
    let target = fp"{root}/docs/{doc.rel}"
    if ! target.exists()? or target.read_text()? != doc.text {
      target.parent().mkdir()?
      target.write(doc.text)?
      print f"wrote docs/{doc.rel}"
    }
  }
}

## Fails when committed generated docs differ from a fresh render, when a
## snippet's check diagnostics differ from its `# error: CODE` comments, or when
## the tour project's tests fail.
export proc check(root: Path, tools: DocTools) [fs, process, env, error, io] -> Result[Unit] {
  let stale = [
    f"docs/{doc.rel}"
    for doc in render(root, tools)?
    if ! fp"{root}/docs/{doc.rel}".exists()? or fp"{root}/docs/{doc.rel}".read_text()? != doc.text
  ]
  guard stale.len() == 0 else {
    return Err(DocsError.Stale(message: f"stale generated docs: {stale.join(", ")}; run `make docs`"))
  }

  for collection in snippet_collections {
    check_snippet_diagnostics(fp"{root}/docs/snippets/{collection}", tools.xsht)?
  }

  stages.execute(
    stages.command(
      "check-docs-project",
      "docs",
      tools.xsht.display(),
      [tools.xsht.display(), "test"],
      fp"{root}/docs/snippets/tour/project",
      {},
    ),
  )?
}

## Release binaries for `make docs` and `cargo dev check`, built by
## `build_release` or the `check-build` stage.
export pure release_tools(ctx: context.Context) -> DocTools {
  DocTools(xsh: fp"{ctx.target_dir}/release/xsh", xsht: fp"{ctx.target_dir}/release/xsht")
}

## Builds the release `xsh` and `xsht` that render the docs.
export proc build_release(ctx: context.Context) [process, error, io] -> Result[Unit] {
  stages.execute(
    stages.command(
      "docs-build",
      ctx.target.triple,
      "cargo",
      [
        "cargo",
        "build",
        "--release",
        "-p",
        "xsh",
        "--bin",
        "xsh",
        "-p",
        "xsht",
        "--bin",
        "xsht",
      ],
      ctx.root,
      {},
    ),
  )?
}
