##! Generated documentation: renders each `docs/templates/REL` into `docs/REL`
##! with the stdlib `template` module, and checks that committed output is current.
##!
##! Template data is one record:
##! - `snippets.NAME`: `{source, output, platform}` for `docs/snippets/tour/NN-NAME.xsh`
##!   (`-` in NAME becomes `_`). `output` is the snippet's stdout when some template
##!   references `.snippets.NAME.output`, and null otherwise, so only shown outputs run.
##!   A snippet whose first line is `# platform: linux` is checked but never run; any
##!   output shown for it is literal text in the template.
##! - `project.KEY`: `{path, source}` for each file of `docs/snippets/tour/project/`,
##!   keyed by its relative path without the extension, non-alphanumeric runs as `_`.
##! - `stdlib`, `cli`, `lints`: reference data read from `xsht api`, the binaries'
##!   help, and `xsht lint --list`.
use context
use stage as stages

## A generated-documentation failure, rendered at the development command boundary.
export error DocsError = Stale(message: Str) | Snippet(message: Str) | Layout(message: Str)

## The binaries that render and verify the documentation.
export type DocTools = {xsh: Path, xsht: Path}

type Snippet = {source: Str, output: Str?, platform: Str}

type ProjectFile = {path: Str, source: Str}

type Rendered = {rel: Str, text: Str}

type Overloads = {name: Str, overloads: Int}

type ModuleIndex = {name: Str, functions: List[Overloads]}

type ReceiverIndex = {name: Str, methods: List[Overloads]}

type ApiSummary = {modules: List[ModuleIndex], method_receivers: List[ReceiverIndex], records: List[Str]}

type ApiMatch = {kind: Str, summary: Str, signatures: List[Str]}

type ApiAnswer = {query: Str, matches: List[ApiMatch]}

type IndexLine = {signature: Str, summary: Str}

type LintCode = {code: Str, summary: Str}

const snippet_name = rx"^[0-9][0-9]-([a-z0-9-]+)\.xsh$"

const output_reference = rx"\.snippets\.[a-z0-9_]+\.output"

const command_heading = rx"^([a-z]+) — "

# Modules that are internal host support rather than user API.
const internal_modules = ["applet"]

pure header(rel: Str) -> Str {
  let hint = if rel == "user-tour.md" {
    "edit the template and docs/snippets/tour/."
  } else {
    "edit the template or the code it documents."
  }
  f"<!-- Generated by make docs from docs/templates/${rel}; ${hint} -->"
}

# Text without its final newline, for embedding between fence lines.
pure body(text: Str) -> Str {
  text.lines().join("\n")
}

pure field_key(rel: Str) -> Str {
  rx"[^A-Za-z0-9]+".replace(rx"\.[A-Za-z0-9]+$".replace(rel, ""), "_")
}

pure shown_outputs(templates: List[Str]) -> List[Str] {
  var names: List[Str] = []
  for source in templates {
    for found in output_reference.find(source) {
      names += [found.text.split(".")[2]]
    }
  }

  names
}

# Runs a trusted repository snippet in an empty directory with only `PATH` set.
# The child gets its working directory from its command plan rather than a
# `cd` scope, which would serialize the `par-map` workers.
proc run_snippet(xsh: Path, file: Path, search_path: Str) [fs, process, error] -> Result[Str] {
  let sandbox = fs.tempdir()?
  defer sandbox.close()?
  let capture = fs.tempdir()?
  defer capture.close()?
  let stdout = fp"${capture.host_path()?}/stdout"
  let stderr = fp"${capture.host_path()?}/stderr"
  let argv = ["-i", f"PATH=${search_path}", xsh.display(), file.display()]
  let plan = process.command_argv(/usr/bin/env, argv, cwd: sandbox.host_path()?, stdout:, stderr:, timeout: 60s)
  guard process.run(plan)?.ok else {
    return Err(DocsError.Snippet(message: f"${file.name()} failed: ${stderr.read_text()?.trim()}"))
  }

  body(stdout.read_text()?)
}

proc snippets(root: Path, xsh: Path, shown: List[Str]) [fs, process, env, error] -> Result[Map[Str, Snippet]] {
  let search_path = env.get_or("PATH", "")?
  let files = fs.files(fp"${root}/docs/snippets/tour", exts: ["xsh"])?
    |> where .path.parent().name() == "tour"
    |> sort-by .name
  let collected = files
    |> par-map(jobs: 8) { |entry|
      let parts = snippet_name.captures(entry.name)
      guard parts.len() == 2 else {
        return Err(DocsError.Layout(message: f"snippet ${entry.name} is not named NN-name.xsh"))
      }

      let name = parts[1].replace("-", "_")
      let source = entry.path.read_text()?
      let platform = if (source.lines().get(0) ?? "") == "# platform: linux" { "linux" } else { "any" }
      let output: Str? = if name not in shown {
        null
      } else if platform != "any" {
        return Err(
          DocsError.Snippet(message: f"a template shows the output of platform-specific ${entry.name}"),
        )
      } else {
        run_snippet(xsh, entry.path, search_path)?
      }

      {name, snippet: Snippet(source: body(source), output:, platform:)}
    }

  var table: Map[Str, Snippet] = {}
  for {name, snippet} in collected {
    guard name not in table else {
      return Err(DocsError.Layout(message: f"two tour snippets are named ${name}"))
    }

    table[name] = snippet
  }

  for name in shown {
    guard name in table else {
      return Err(DocsError.Layout(message: f"a template shows the output of unknown snippet ${name}"))
    }
  }

  table
}

proc project(root: Path) [fs, error] -> Result[Map[Str, ProjectFile]] {
  let base = fp"${root}/docs/snippets/tour/project"
  var files: Map[Str, ProjectFile] = {}
  for entry in fs.files(base)? {
    let rel = entry.path.relative_to(base).display()
    files[field_key(rel)] = ProjectFile(path: rel, source: body(entry.path.read_text()?))
  }

  files
}

pure index_line(found: ApiMatch) -> IndexLine {
  let extra = found.signatures.len() - 1
  let signature = found.signatures.get(0) ?? ""
  let suffix = if extra > 0 { f" (+${extra} overloads)" } else { "" }
  IndexLine(signature: signature + suffix, summary: found.summary)
}

proc stdlib(xsht: Path) [process, error] -> Result[Record] {
  let summary = json.decode(run.text $xsht api summary --format jsonl?)?.require(ApiSummary)?
  let modules = [m for m in summary.modules if m.name not in internal_modules]
  var queries = [f"module:${m.name}" for m in modules]
  for receiver in summary.method_receivers {
    let owner = receiver.name.fields()[0]
    queries += [f"method:${owner}.${m.name}" for m in receiver.methods if " " not in m.name]
  }

  queries += [f"record:${name}" for name in summary.records]

  var answers: Map[Str, List[ApiMatch]] = {}
  for line in (run.text $xsht api --strict --format jsonl @queries)?.lines() {
    let answer = json.decode(line)?.require(ApiAnswer)?
    answers[answer.query] = answer.matches
  }

  var module_rows = []
  for m in modules {
    let matches = answers[f"module:${m.name}"]
    module_rows += [
      {
        name: m.name,
        summary: [found.summary for found in matches if found.kind == "module"].get(0) ?? "",
        functions: [index_line(found) for found in matches if found.kind == "module-function"],
      },
    ]
  }

  var receiver_rows = []
  for receiver in summary.method_receivers {
    let owner = receiver.name.fields()[0]
    let lines = [
      index_line(found)
      for m in receiver.methods
      if " " not in m.name
      for found in answers[f"method:${owner}.${m.name}"]
    ]
    receiver_rows += [{name: receiver.name, methods: lines}]
  }

  let records = [
    index_line(found)
    for name in summary.records
    for found in answers[f"record:${name}"]
  ]
  {modules: module_rows, receivers: receiver_rows, records}
}

# Help text without its leading `NAME VERSION` line, so releases do not stale the reference.
pure unversioned(help: Str) -> Str {
  body(help).lines()[1..].join("\n").trim()
}

pure line_index(lines: List[Str], heading: Str) -> Int {
  for index in range(lines.len()) {
    return index when lines[index] == heading
  }

  -1
}

proc cli_reference(tools: DocTools) [process, error] -> Result[Record] {
  let lines = unversioned(run.text $tools.xsht --help?).lines()
  let reference = line_index(lines, "Command reference:")
  let workflows = line_index(lines, "Common workflows:")
  guard 0 < reference < workflows else {
    return Err(DocsError.Layout(message: "`xsht --help` lacks its command reference or workflows section"))
  }

  var commands = []
  for line in lines[reference..workflows] {
    if let [_, name] = command_heading.captures(line) {
      commands += [{name, help: body(run.text $tools.xsht help $name?)}]
    }
  }

  {
    xsh: unversioned(run.text $tools.xsh --help?),
    xsht: lines[..reference].join("\n").trim(),
    commands,
    workflows: [line for line in lines[workflows + 1..] if line != ""].join("\n"),
  }
}

proc lints(xsht: Path) [process, error] -> Result[List[LintCode]] {
  [json.decode(line)?.require(LintCode)? for line in (run.text $xsht lint --list --format jsonl)?.lines()]
}

# Renders every template with freshly collected data.
proc render(root: Path, tools: DocTools) [fs, process, env, error] -> Result[List[Rendered]] {
  let templates_dir = fp"${root}/docs/templates"
  let templates = fs.files(templates_dir, exts: ["md"])? |> sort-by .name
  let sources = [{rel: t.path.relative_to(templates_dir).display(), source: t.path.read_text()?} for t in templates]
  let data = {
    snippets: snippets(root, tools.xsh, shown_outputs([t.source for t in sources]))?,
    project: project(root)?,
    stdlib: stdlib(tools.xsht)?,
    cli: cli_reference(tools)?,
    lints: lints(tools.xsht)?,
  }

  [Rendered(
    rel: t.rel,
    text: [
      header(t.rel),
      "",
      ctx f"rendering docs/templates/${t.rel}" {
        template.render(t.source, data)?
      },
    ].join("\n"),
  ) for t in sources]
}

## Regenerates every generated document under `docs/`, rewriting only files that changed.
export proc generate(root: Path, tools: DocTools) [fs, process, env, error, io] -> Result[Unit] {
  for doc in render(root, tools)? {
    let target = fp"${root}/docs/${doc.rel}"
    if ! target.exists()? or target.read_text()? != doc.text {
      target.parent().mkdir()?
      target.write(doc.text)?
      print f"wrote docs/${doc.rel}"
    }
  }
}

## Fails when committed generated docs differ from a fresh render, or when the
## tour snippets stop checking or the tour project's tests fail.
export proc check(root: Path, tools: DocTools) [fs, process, env, error, io] -> Result[Unit] {
  let stale = [
    f"docs/${doc.rel}"
    for doc in render(root, tools)?
    if ! fp"${root}/docs/${doc.rel}".exists()? or fp"${root}/docs/${doc.rel}".read_text()? != doc.text
  ]
  guard stale.len() == 0 else {
    return Err(DocsError.Stale(message: f"stale generated docs: ${stale.join(", ")}; run `make docs`"))
  }

  let tour = fp"${root}/docs/snippets/tour"
  stages.execute(
    stages.command(
      "check-docs-snippets",
      "docs",
      tools.xsht.display(),
      [tools.xsht.display(), "check", tour.display()],
      root,
      {},
    ),
  )?
  stages.execute(
    stages.command(
      "check-docs-project",
      "docs",
      tools.xsht.display(),
      [tools.xsht.display(), "test"],
      fp"${tour}/project",
      {},
    ),
  )?
}

## Release binaries for `make docs`, built by `build_release`.
export pure release_tools(ctx: context.Context) -> DocTools {
  DocTools(xsh: fp"${ctx.target_dir}/release/xsh", xsht: fp"${ctx.target_dir}/release/xsht")
}

## Debug binaries, as built by the `check-build` stage.
export pure debug_tools(ctx: context.Context) -> DocTools {
  DocTools(xsh: fp"${ctx.target_dir}/debug/xsh", xsht: fp"${ctx.target_dir}/debug/xsht")
}

## Builds the release `xsh` and `xsht` that render the docs.
export proc build_release(ctx: context.Context) [process, error, io] -> Result[Unit] {
  stages.execute(
    stages.command(
      "docs-build",
      ctx.target.triple,
      "cargo",
      [
        "cargo",
        "build",
        "--release",
        "-p",
        "xsh",
        "--bin",
        "xsh",
        "-p",
        "xsht",
        "--bin",
        "xsht",
      ],
      ctx.root,
      {},
    ),
  )?
}
