[package]
name = "xsh-net"
version = "0.0.1"
edition = "2024"
publish = false

[lints]
workspace = true

[dependencies]
cap-net-ext = "4.0.2"
cap-std = "4.0.2"
crossbeam-channel = "0.5"
libc = "0.2"
rustc-hash = "2.1.2"
rustls = { version = "0.23.40", default-features = false, features = ["aws_lc_rs", "std", "tls12"] }
rustls-platform-verifier = "0.7.0"
rustls-pemfile = "2"
