//! Record schemas and the constant table of the Linux socket, netlink, and
//! ioctl boundary. The table is shared with the runtime so the record type a
//! script sees and the values it receives cannot drift apart.

use crate::types::Type;
use std::collections::BTreeMap;

fn record(fields: impl IntoIterator<Item = (&'static str, Type)>) -> Type {
    Type::Record(fields.into_iter().map(|(name, ty)| (name.to_string(), ty)).collect())
}

/// Linux socket, option, netlink, and ioctl numbers that a script needs by
/// name. The values are the generic-architecture kernel ABI, which x86-64 and
/// AArch64 share; sizes of pointer-bearing structures differ on 32-bit hosts
/// and are listed separately.
pub const NET_CONSTANTS: &[(&str, i64)] = &[
    ("AF_UNSPEC", 0),
    ("AF_UNIX", 1),
    ("AF_INET", 2),
    ("AF_INET6", 10),
    ("AF_NETLINK", 16),
    ("AF_PACKET", 17),
    ("SOCK_STREAM", 1),
    ("SOCK_DGRAM", 2),
    ("SOCK_RAW", 3),
    ("SOCK_SEQPACKET", 5),
    ("SOCK_NONBLOCK", 2048),
    ("SOCK_CLOEXEC", 524288),
    ("IPPROTO_IP", 0),
    ("IPPROTO_ICMP", 1),
    ("IPPROTO_TCP", 6),
    ("IPPROTO_UDP", 17),
    ("IPPROTO_IPV6", 41),
    ("IPPROTO_ICMPV6", 58),
    ("IPPROTO_RAW", 255),
    ("SOL_SOCKET", 1),
    ("SOL_IP", 0),
    ("SOL_TCP", 6),
    ("SOL_UDP", 17),
    ("SOL_IPV6", 41),
    ("SOL_ICMPV6", 58),
    ("SOL_RAW", 255),
    ("SOL_PACKET", 263),
    ("SOL_NETLINK", 270),
    ("SO_DEBUG", 1),
    ("SO_REUSEADDR", 2),
    ("SO_TYPE", 3),
    ("SO_ERROR", 4),
    ("SO_DONTROUTE", 5),
    ("SO_BROADCAST", 6),
    ("SO_SNDBUF", 7),
    ("SO_RCVBUF", 8),
    ("SO_KEEPALIVE", 9),
    ("SO_OOBINLINE", 10),
    ("SO_PRIORITY", 12),
    ("SO_LINGER", 13),
    ("SO_REUSEPORT", 15),
    ("SO_PASSCRED", 16),
    ("SO_PEERCRED", 17),
    ("SO_RCVLOWAT", 18),
    ("SO_SNDLOWAT", 19),
    ("SO_RCVTIMEO", 20),
    ("SO_SNDTIMEO", 21),
    ("SO_BINDTODEVICE", 25),
    ("SO_ATTACH_FILTER", 26),
    ("SO_DETACH_FILTER", 27),
    ("SO_TIMESTAMP", 29),
    ("SO_ACCEPTCONN", 30),
    ("SO_SNDBUFFORCE", 32),
    ("SO_RCVBUFFORCE", 33),
    ("SO_TIMESTAMPNS", 35),
    ("SO_MARK", 36),
    ("SO_PROTOCOL", 38),
    ("SO_DOMAIN", 39),
    ("SO_RXQ_OVFL", 40),
    ("SO_BUSY_POLL", 46),
    ("SO_BINDTOIFINDEX", 62),
    ("IP_TOS", 1),
    ("IP_TTL", 2),
    ("IP_HDRINCL", 3),
    ("IP_OPTIONS", 4),
    ("IP_PKTINFO", 8),
    ("IP_MTU_DISCOVER", 10),
    ("IP_RECVERR", 11),
    ("IP_RECVTTL", 12),
    ("IP_RECVTOS", 13),
    ("IP_MTU", 14),
    ("IP_FREEBIND", 15),
    ("IP_TRANSPARENT", 19),
    ("IP_RECVORIGDSTADDR", 20),
    ("IP_MULTICAST_IF", 32),
    ("IP_MULTICAST_TTL", 33),
    ("IP_MULTICAST_LOOP", 34),
    ("IP_ADD_MEMBERSHIP", 35),
    ("IP_DROP_MEMBERSHIP", 36),
    ("IP_BIND_ADDRESS_NO_PORT", 24),
    ("IP_PMTUDISC_DONT", 0),
    ("IP_PMTUDISC_WANT", 1),
    ("IP_PMTUDISC_DO", 2),
    ("IP_PMTUDISC_PROBE", 3),
    ("IPV6_UNICAST_HOPS", 16),
    ("IPV6_MULTICAST_IF", 17),
    ("IPV6_MULTICAST_HOPS", 18),
    ("IPV6_MULTICAST_LOOP", 19),
    ("IPV6_JOIN_GROUP", 20),
    ("IPV6_LEAVE_GROUP", 21),
    ("IPV6_MTU_DISCOVER", 23),
    ("IPV6_MTU", 24),
    ("IPV6_RECVERR", 25),
    ("IPV6_V6ONLY", 26),
    ("IPV6_RECVPKTINFO", 49),
    ("IPV6_PKTINFO", 50),
    ("IPV6_RECVHOPLIMIT", 51),
    ("IPV6_HOPLIMIT", 52),
    ("IPV6_RECVTCLASS", 66),
    ("IPV6_TCLASS", 67),
    ("IPV6_CHECKSUM", 7),
    ("IPV6_DONTFRAG", 62),
    ("IPV6_PMTUDISC_DONT", 0),
    ("IPV6_PMTUDISC_DO", 2),
    ("IPV6_PMTUDISC_PROBE", 3),
    ("ICMP_FILTER", 1),
    ("ICMPV6_FILTER", 1),
    ("TCP_NODELAY", 1),
    ("TCP_MAXSEG", 2),
    ("TCP_CORK", 3),
    ("TCP_KEEPIDLE", 4),
    ("TCP_KEEPINTVL", 5),
    ("TCP_KEEPCNT", 6),
    ("TCP_SYNCNT", 7),
    ("TCP_LINGER2", 8),
    ("TCP_DEFER_ACCEPT", 9),
    ("TCP_WINDOW_CLAMP", 10),
    ("TCP_INFO", 11),
    ("TCP_QUICKACK", 12),
    ("TCP_CONGESTION", 13),
    ("TCP_USER_TIMEOUT", 18),
    ("TCP_FASTOPEN", 23),
    ("TCP_NOTSENT_LOWAT", 25),
    ("TCP_ESTABLISHED", 1),
    ("TCP_SYN_SENT", 2),
    ("TCP_SYN_RECV", 3),
    ("TCP_FIN_WAIT1", 4),
    ("TCP_FIN_WAIT2", 5),
    ("TCP_TIME_WAIT", 6),
    ("TCP_CLOSE", 7),
    ("TCP_CLOSE_WAIT", 8),
    ("TCP_LAST_ACK", 9),
    ("TCP_LISTEN", 10),
    ("TCP_CLOSING", 11),
    ("MSG_OOB", 1),
    ("MSG_PEEK", 2),
    ("MSG_DONTROUTE", 4),
    ("MSG_CTRUNC", 8),
    ("MSG_TRUNC", 32),
    ("MSG_DONTWAIT", 64),
    ("MSG_EOR", 128),
    ("MSG_WAITALL", 256),
    ("MSG_NOSIGNAL", 16384),
    ("MSG_ERRQUEUE", 8192),
    ("SHUT_RD", 0),
    ("SHUT_WR", 1),
    ("SHUT_RDWR", 2),
    ("SO_EE_ORIGIN_NONE", 0),
    ("SO_EE_ORIGIN_LOCAL", 1),
    ("SO_EE_ORIGIN_ICMP", 2),
    ("SO_EE_ORIGIN_ICMP6", 3),
    ("NETLINK_ROUTE", 0),
    ("NETLINK_USERSOCK", 2),
    ("NETLINK_FIREWALL", 3),
    ("NETLINK_SOCK_DIAG", 4),
    ("NETLINK_XFRM", 6),
    ("NETLINK_SELINUX", 7),
    ("NETLINK_AUDIT", 9),
    ("NETLINK_FIB_LOOKUP", 10),
    ("NETLINK_CONNECTOR", 11),
    ("NETLINK_NETFILTER", 12),
    ("NETLINK_KOBJECT_UEVENT", 15),
    ("NETLINK_GENERIC", 16),
    ("NLM_F_REQUEST", 1),
    ("NLM_F_MULTI", 2),
    ("NLM_F_ACK", 4),
    ("NLM_F_ECHO", 8),
    ("NLM_F_DUMP_INTR", 16),
    ("NLM_F_DUMP_FILTERED", 32),
    ("NLM_F_ROOT", 256),
    ("NLM_F_MATCH", 512),
    ("NLM_F_ATOMIC", 1024),
    ("NLM_F_DUMP", 768),
    ("NLM_F_REPLACE", 256),
    ("NLM_F_EXCL", 512),
    ("NLM_F_CREATE", 1024),
    ("NLM_F_APPEND", 2048),
    ("NLMSG_NOOP", 1),
    ("NLMSG_ERROR", 2),
    ("NLMSG_DONE", 3),
    ("NLMSG_OVERRUN", 4),
    ("RTM_NEWLINK", 16),
    ("RTM_DELLINK", 17),
    ("RTM_GETLINK", 18),
    ("RTM_NEWADDR", 20),
    ("RTM_DELADDR", 21),
    ("RTM_GETADDR", 22),
    ("RTM_NEWROUTE", 24),
    ("RTM_DELROUTE", 25),
    ("RTM_GETROUTE", 26),
    ("RTM_NEWNEIGH", 28),
    ("RTM_DELNEIGH", 29),
    ("RTM_GETNEIGH", 30),
    ("RTM_NEWRULE", 32),
    ("RTM_DELRULE", 33),
    ("RTM_GETRULE", 34),
    ("RTMGRP_LINK", 1),
    ("RTMGRP_IPV4_IFADDR", 16),
    ("RTMGRP_IPV4_ROUTE", 64),
    ("RTMGRP_IPV6_IFADDR", 256),
    ("RTMGRP_IPV6_ROUTE", 1024),
    ("SOCK_DIAG_BY_FAMILY", 20),
    ("SOCK_DESTROY", 21),
    ("INET_DIAG_INFO", 2),
    ("INET_DIAG_CONG", 4),
    ("INET_DIAG_TOS", 5),
    ("INET_DIAG_TCLASS", 6),
    ("INET_DIAG_SKMEMINFO", 7),
    ("INET_DIAG_SHUTDOWN", 8),
    ("INET_DIAG_PROTOCOL", 10),
    ("GENL_ID_CTRL", 16),
    ("CTRL_CMD_GETFAMILY", 3),
    ("CTRL_ATTR_FAMILY_ID", 1),
    ("CTRL_ATTR_FAMILY_NAME", 2),
    ("CTRL_ATTR_VERSION", 3),
    ("CTRL_ATTR_HDRSIZE", 4),
    ("CTRL_ATTR_MAXATTR", 5),
    ("CTRL_ATTR_MCAST_GROUPS", 7),
    ("IFF_UP", 1),
    ("IFF_BROADCAST", 2),
    ("IFF_DEBUG", 4),
    ("IFF_LOOPBACK", 8),
    ("IFF_POINTOPOINT", 16),
    ("IFF_NOTRAILERS", 32),
    ("IFF_RUNNING", 64),
    ("IFF_NOARP", 128),
    ("IFF_PROMISC", 256),
    ("IFF_ALLMULTI", 512),
    ("IFF_MASTER", 1024),
    ("IFF_SLAVE", 2048),
    ("IFF_MULTICAST", 4096),
    ("IFF_LOWER_UP", 65536),
    ("IFF_DORMANT", 131072),
    ("ARPHRD_ETHER", 1),
    ("ARPHRD_LOOPBACK", 772),
    ("ATF_COM", 2),
    ("ATF_PERM", 4),
    ("ATF_PUBL", 8),
    ("IFNAMSIZ", 16),
    ("SIOCGIFNAME", 35088),
    ("SIOCGIFFLAGS", 35091),
    ("SIOCSIFFLAGS", 35092),
    ("SIOCGIFADDR", 35093),
    ("SIOCSIFADDR", 35094),
    ("SIOCGIFDSTADDR", 35095),
    ("SIOCSIFDSTADDR", 35096),
    ("SIOCGIFBRDADDR", 35097),
    ("SIOCSIFBRDADDR", 35098),
    ("SIOCGIFNETMASK", 35099),
    ("SIOCSIFNETMASK", 35100),
    ("SIOCGIFMETRIC", 35101),
    ("SIOCSIFMETRIC", 35102),
    ("SIOCGIFMTU", 35105),
    ("SIOCSIFMTU", 35106),
    ("SIOCSIFNAME", 35107),
    ("SIOCGIFHWADDR", 35111),
    ("SIOCSIFHWADDR", 35108),
    ("SIOCGIFTXQLEN", 35138),
    ("SIOCSIFTXQLEN", 35139),
    ("SIOCGIFINDEX", 35123),
    ("SIOCGIFMAP", 35184),
    ("SIOCETHTOOL", 35142),
    ("SIOCGMIIPHY", 35143),
    ("SIOCGMIIREG", 35144),
    ("SIOCGARP", 35156),
    ("SIOCSARP", 35157),
    ("SIOCDARP", 35155),
    ("SIOCGIWNAME", 35585),
    ("SIOCINQ", 21531),
    ("SIOCOUTQ", 21521),
    ("ETHTOOL_GSET", 1),
    ("ETHTOOL_SSET", 2),
    ("ETHTOOL_GDRVINFO", 3),
    ("ETHTOOL_GWOL", 5),
    ("ETHTOOL_GMSGLVL", 7),
    ("ETHTOOL_GLINK", 10),
    ("ETHTOOL_GSTRINGS", 27),
    ("ETHTOOL_GSTATS", 29),
    ("ETHTOOL_GPERMADDR", 32),
    ("ETHTOOL_GLINKSETTINGS", 76),
    ("ETHTOOL_GSSET_INFO", 55),
    ("ETHTOOL_GRINGPARAM", 16),
    ("ETHTOOL_GPAUSEPARAM", 18),
    ("ETHTOOL_GCOALESCE", 14),
    ("IFREQ_SIZE", if cfg!(target_pointer_width = "64") { 40 } else { 32 }),
    ("ARPREQ_SIZE", 68),
];

pub fn linux_net_constants_type() -> Type {
    record(NET_CONSTANTS.iter().map(|(name, _)| (*name, Type::Int)))
}

pub fn linux_socket_address_type() -> Type {
    record([
        ("family", Type::Str),
        ("address", Type::Str),
        ("port", Type::Int),
        ("scope_id", Type::Int),
        ("raw", Type::Bytes),
    ])
}

pub fn linux_accepted_socket_type() -> Type {
    record([("fd", Type::Int), ("peer", linux_socket_address_type())])
}

pub fn linux_control_message_type() -> Type {
    record([("level", Type::Int), ("type", Type::Int), ("data", Type::Bytes)])
}

pub fn linux_received_message_type() -> Type {
    record([
        ("data", Type::Bytes),
        ("address", linux_socket_address_type()),
        ("flags", Type::Int),
        ("control", Type::List(Box::new(linux_control_message_type()))),
    ])
}

pub fn linux_netlink_message_type() -> Type {
    record([
        ("type", Type::Int),
        ("flags", Type::Int),
        ("seq", Type::Int),
        ("pid", Type::Int),
        ("payload", Type::Bytes),
    ])
}

/// The address forms a script may pass in: a typed record or raw `sockaddr`
/// bytes for families the record does not cover.
pub fn linux_socket_address_argument_type() -> Type {
    Type::Union(vec![Type::Record(BTreeMap::new()), Type::Bytes])
}
