#[path = "app.rs"]
pub mod app;
#[path = "cli/mod.rs"]
pub mod cli;
#[path = "config.rs"]
pub(crate) mod config;
#[path = "docs.rs"]
pub mod docs;
#[path = "edit.rs"]
pub(crate) mod edit;
#[path = "format.rs"]
pub mod format;
#[path = "grep.rs"]
pub mod grep;
#[path = "lint.rs"]
pub mod lint;
#[path = "xsht/test.rs"]
pub(crate) mod test;
